# Generated by Django 5.2 on 2025-04-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "char_class",
                    models.CharField(
                        choices=[
                            ("barbarian", "Barbarian"),
                            ("bard", "Bard"),
                            ("cleric", "Cleric"),
                            ("druid", "Druid"),
                            ("fighter", "Fighter"),
                            ("monk", "Monk"),
                            ("paladin", "Paladin"),
                            ("ranger", "Ranger"),
                            ("rogue", "Rogue"),
                            ("sorcerer", "Sorcerer"),
                            ("warlock", "Warlock"),
                            ("wizard", "Wizard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subclass", models.CharField(blank=True, max_length=40)),
                ("race", models.CharField(max_length=40)),
                ("background", models.CharField(blank=True, max_length=40)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                (
                    "alignment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LG", "Lawful Good"),
                            ("NG", "Neutral Good"),
                            ("CG", "Chaotic Good"),
                            ("LN", "Lawful Neutral"),
                            ("N", "Neutral"),
                            ("CN", "Chaotic Neutral"),
                            ("LE", "Lawful Evil"),
                            ("NE", "Neutral Evil"),
                            ("CE", "Chaotic Evil"),
                        ],
                        max_length=2,
                    ),
                ),
                ("strength", models.PositiveSmallIntegerField(default=10)),
                ("dexterity", models.PositiveSmallIntegerField(default=10)),
                ("constitution", models.PositiveSmallIntegerField(default=10)),
                ("intelligence", models.PositiveSmallIntegerField(default=10)),
                ("wisdom", models.PositiveSmallIntegerField(default=10)),
                ("charisma", models.PositiveSmallIntegerField(default=10)),
                ("hp_max", models.PositiveSmallIntegerField(default=1)),
                ("hp_current", models.PositiveSmallIntegerField(default=1)),
                ("temp_hp", models.PositiveSmallIntegerField(default=0)),
                ("armor_class", models.PositiveSmallIntegerField(default=10)),
                ("initiative", models.SmallIntegerField(default=0)),
                ("speed", models.PositiveSmallIntegerField(default=30)),
                ("proficiency_bonus", models.SmallIntegerField(default=2)),
                ("passive_perception", models.SmallIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "unique_together": {("user", "name")},
            },
        ),
    ]
