# Generated by Django 4.2.20 on 2025-04-27 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="conditions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="Lista di condizioni attive sul personaggio.",
                size=None,
            ),
        ),
    ]
