# Generated by Django 4.2.20 on 2025-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="summary_cache",
        ),
        migrations.AddField(
            model_name="session",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
