# Generated by Django 4.2.20 on 2025-04-27 10:29

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_session_summary_cache_session_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="initiative",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "draft"),
                    ("active", "active"),
                    ("paused", "paused"),
                    ("finished", "finished"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
    ]
