# Generated by Django 4.2.20 on 2025-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_session_initiative_alter_session_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="current_turn",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
